### ISSUE TITLE
No transition Mode edit > marquee

### ISSUE THREAD

**Issue by Pabrisson** [guilhermesgb/ShiftableEditText#21]
![screencast](https://cloud.githubusercontent.com/assets/3072789/17903421/b634eca2-696b-11e6-83f8-d8aa5b14fcdc.gif)
Hey,

First, thanks for the library. I have a problem with the mode change. Let me explain. 
After entering a text, it is impossible to reselect to change.

Above a GIF to better explain my point.

Sorry for my bad English.

**Comment by xibaca** [comment]
Thank you for giving this library a try!
So, actually there is a transition but currently you must _long press_ the
widget in order to switch it back to edit mode (or call `setMode(EDIT)`).

In the future, I plan on making this widget more customizable so that the
user can configure the touch event it wants to use for this task.

I'll then close this issue. Feel free to open a new issue if you feel like
the widget should be more customizable and allow you to switch back to EDIT
mode with a single tap.

Thanks again and cheers! :)
